VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Replicate"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Class Module: Replicate
' ************************************************************************

' Properties
' ************************************************************************
Private iReplicateNum As Integer
Private iSampleBarcode As Integer
Private dReplicateAEB As Double
Private dReplicateConc As Double
Private vErrors As Variant
Private sWellLocation As String
Private sPlateLocation As String
Private bPositive As Boolean



' Get/Set Properties
' ************************************************************************



' Methods
' ************************************************************************

